"""create generations table

Revision ID: 8251d928b0b4
Revises: 96beec6e89b5
Create Date: 2026-05-10 18:52:00.511712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8251d928b0b4'
down_revision: Union[str, Sequence[str], None] = '96beec6e89b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('video_type', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('generated_title', sa.Text(), nullable=True),
    sa.Column('generated_hook', sa.Text(), nullable=True),
    sa.Column('generated_script', sa.Text(), nullable=True),
    sa.Column('generated_cta', sa.Text(), nullable=True),
    sa.Column('generated_storyboard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generations')
    # ### end Alembic commands ###
